"""
Manual Google Sheets Setup Guide
Since the API has restrictions, follow these steps to create the sheets manually
"""

print("=" * 70)
print("📋 MANUAL GOOGLE SHEETS SETUP")
print("=" * 70)
print()
print("Since the Google Sheets API has restrictions, please create the sheets")
print("manually following these steps:")
print()
print("=" * 70)
print("1️⃣  CREATE PLANS SPREADSHEET")
print("=" * 70)
print()
print("1. Go to: https://drive.google.com/drive/folders/1vgeveIrbdo12egt-RG2NbdZppsnEmLty")
print("2. Click 'New' → 'Google Sheets' → 'Blank spreadsheet'")
print("3. Name it: 'VenridesScreenS - Contrataciones'")
print()
print("4. Create 5 sheets (tabs) with these names:")
print("   - Free")
print("   - Basico")
print("   - Plus")
print("   - Ultra")
print("   - Empresarial")
print()
print("5. In EACH sheet, add these headers in row 1:")
print("   A: Timestamp")
print("   B: Nombre Completo")
print("   C: Email")
print("   D: Teléfono")
print("   E: Empresa/Negocio")
print("   F: Tipo de Negocio")
print("   G: Pantallas Estimadas")
print("   H: Mensaje/Comentarios")
print("   I: Estado")
print("   J: Fecha Actualización")
print()
print("6. Format row 1 (headers):")
print("   - Bold text")
print("   - Background color: Light blue (#00CCFF)")
print()
print("7. Copy the Spreadsheet ID from the URL:")
print("   https://docs.google.com/spreadsheets/d/[THIS_IS_THE_ID]/edit")
print()
print("=" * 70)
print("2️⃣  CREATE CONTACT SPREADSHEET")
print("=" * 70)
print()
print("1. Go to: https://drive.google.com/drive/folders/1mQXnR10ijFX8oBcd7hUWXiMdyRhqR8ly")
print("2. Click 'New' → 'Google Sheets' → 'Blank spreadsheet'")
print("3. Name it: 'VenridesScreenS - Contactos'")
print()
print("4. Rename the first sheet to: 'Contactos'")
print()
print("5. Add these headers in row 1:")
print("   A: Timestamp")
print("   B: Nombre Completo")
print("   C: Email")
print("   D: Teléfono")
print("   E: Asunto")
print("   F: Mensaje")
print("   G: Estado")
print("   H: Fecha Actualización")
print()
print("6. Format row 1 (headers):")
print("   - Bold text")
print("   - Background color: Light blue (#00CCFF)")
print()
print("7. Copy the Spreadsheet ID from the URL:")
print("   https://docs.google.com/spreadsheets/d/[THIS_IS_THE_ID]/edit")
print()
print("=" * 70)
print("3️⃣  UPDATE .ENV FILE")
print("=" * 70)
print()
print("Edit: /home/nerdop/VenridesScreenS/backend/.env")
print()
print("Add the two Spreadsheet IDs:")
print("PLANS_SHEET_ID=<paste_plans_spreadsheet_id_here>")
print("CONTACT_SHEET_ID=<paste_contact_spreadsheet_id_here>")
print()
print("=" * 70)
print("✅ DONE!")
print("=" * 70)
print()
print("Once you've completed these steps, the forms will work correctly!")
print()
